### PR TITLE
Adapt benchmark with Viv loaders and datasets from IDR

### PR DESCRIPTION
**Pull request by manzt**

### CODE REVIEW

**Comment by manzt** [comment]
Oops! Did not mean to open this PR here....

**Comment by manzt** [comment]
Oops! Did not mean to open this PR here....

**Comment by joshmoore** [comment]
> Oops! Did not mean to open this PR here.... not sure if you can delete a PR? Apologies.

I can ask to have it removed if you want, but I think it's great. (I had considered Snakemake as well.)

**Comment by manzt** [comment]
> I can ask to have it removed if you want, but I think it's great. (I had considered Snakemake as well.)

No worries! I meant to submit the PR to my fork (to myself :)), which I've adapted a lot for a Viv related benchmark. No need to delete the PR, but it doesn't make sense to suggest the same changes here!

**Pull request closed without merging**
